# Define the stages of the pipeline
stages:
  - build
  - deploy

# Default settings for all jobs
default:
  image: docker:20.10.16-git # Use a Docker image that has Git and Docker client
  services:
    - name: docker:20.10.16-dind
      alias: docker 
      command: ["--host=tcp://0.0.0.0:2375"]
  tags:
    - docker 

# Variables used throughout the pipeline
variables:
  BACKEND_IMAGE_TAG: $CI_REGISTRY_IMAGE/studyshare-backend:$CI_COMMIT_REF_SLUG
  FRONTEND_IMAGE_TAG: $CI_REGISTRY_IMAGE/studyshare-frontend:$CI_COMMIT_REF_SLUG
  VITE_API_URL_GITLAB_CI: "http://localhost:8080" # Adjust if network setup changes

  # Configure Docker client to connect to the dind service over TLS
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_CERTDIR: ""

  # Proxy configuration for git and other tools within the job environment
  HTTP_PROXY: "http://proxy.hof-university.de:3128"
  HTTPS_PROXY: "http://proxy.hof-university.de:3128"
  NO_PROXY: "localhost,127.0.0.1,docker" # 'docker' is the alias for the dind service

  # Git strategy variables for debugging clone issues
  GIT_STRATEGY: clone
  GIT_DEPTH: "20"
  GIT_TRACE: "1"
  GIT_CURL_VERBOSE: "1"
  GIT_SSL_NO_VERIFY: "false" # Should be false for security

# Job to build the backend Docker image
build_backend:
  stage: build
  before_script:
    - if [ -n "$CI_SERVER_TLS_CA_FILE" ]; then echo "Configuring git with CA file $CI_SERVER_TLS_CA_FILE"; git config --global http.sslCAInfo "$CI_SERVER_TLS_CA_FILE"; else echo "CI_SERVER_TLS_CA_FILE not set"; fi
    - echo "Listing /certs directory..."
    - ls -la /certs || echo "/certs directory does not exist or is empty"
    - echo "Listing /certs/client directory..."
    - ls -la /certs/client || echo "/certs/client directory does not exist or is empty"
    - echo "Waiting for Docker daemon at $DOCKER_HOST..."
    - timeout 60s sh -c 'until docker info > /dev/null 2>&1; do echo -n "."; sleep 1; done'
    - echo "Docker daemon is ready!"
    - docker info
    - echo "Logging into GitLab Registry $CI_REGISTRY"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - echo "Building backend Docker image $BACKEND_IMAGE_TAG"
    - docker build -t $BACKEND_IMAGE_TAG -f backend/Dockerfile backend/
    - echo "Pushing backend image to GitLab Registry"
    - docker push $BACKEND_IMAGE_TAG

# Job to build the frontend Docker image
build_frontend:
  stage: build
  before_script:
    - if [ -n "$CI_SERVER_TLS_CA_FILE" ]; then echo "Configuring git with CA file $CI_SERVER_TLS_CA_FILE"; git config --global http.sslCAInfo "$CI_SERVER_TLS_CA_FILE"; else echo "CI_SERVER_TLS_CA_FILE not set"; fi
    - echo "Listing /certs directory..."
    - ls -la /certs || echo "/certs directory does not exist or is empty"
    - echo "Listing /certs/client directory..."
    - ls -la /certs/client || echo "/certs/client directory does not exist or is empty"
    - echo "Waiting for Docker daemon at $DOCKER_HOST..."
    - timeout 60s sh -c 'until docker info > /dev/null 2>&1; do echo -n "."; sleep 1; done'
    - echo "Docker daemon is ready!"
    - docker info
    - echo "Logging into GitLab Registry $CI_REGISTRY"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - echo "Building frontend Docker image $FRONTEND_IMAGE_TAG"
    - >
      docker build
      --build-arg VITE_API_URL=${VITE_API_URL_GITLAB_CI}
      -t $FRONTEND_IMAGE_TAG -f frontend/Dockerfile frontend/
    - echo "Pushing frontend image to GitLab Registry"
    - docker push $FRONTEND_IMAGE_TAG

# Job to deploy (run) the backend container
deploy_backend:
  stage: deploy
  needs:
    - job: build_backend
      artifacts: false
  before_script:
    - echo "Waiting for Docker daemon at $DOCKER_HOST..."
    - timeout 60s sh -c 'until docker info > /dev/null 2>&1; do echo -n "."; sleep 1; done'
    - echo "Docker daemon is ready!"
    - docker info
    - echo "Logging into GitLab Registry $CI_REGISTRY"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - echo "Pulling backend image from GitLab Registry $BACKEND_IMAGE_TAG"
    - docker pull $BACKEND_IMAGE_TAG
    - echo "Stopping and removing existing backend container if any"
    - docker rm -f studyshare-backend-deploy || true
    - echo "Running backend container"
    - >
      docker run -d --name studyshare-backend-deploy
      -p 8080:8080
      $BACKEND_IMAGE_TAG
    - sleep 10
    - docker ps -f name=studyshare-backend-deploy
    - if [ $(docker ps -f name=studyshare-backend-deploy --format "{{.Names}}") != "studyshare-backend-deploy" ]; then echo "Backend container failed to start"; exit 1; fi

# Job to deploy (run) the frontend container
deploy_frontend:
  stage: deploy
  needs:
    - job: build_frontend
      artifacts: false
  before_script:
    - echo "Waiting for Docker daemon at $DOCKER_HOST..."
    - timeout 60s sh -c 'until docker info > /dev/null 2>&1; do echo -n "."; sleep 1; done'
    - echo "Docker daemon is ready!"
    - docker info
    - echo "Logging into GitLab Registry $CI_REGISTRY"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - echo "Pulling frontend image from GitLab Registry $FRONTEND_IMAGE_TAG"
    - docker pull $FRONTEND_IMAGE_TAG
    - echo "Stopping and removing existing frontend container if any"
    - docker rm -f studyshare-frontend-deploy || true
    - echo "Running frontend container"
    - >
      docker run -d --name studyshare-frontend-deploy
      -p 5173:80
      $FRONTEND_IMAGE_TAG
    - sleep 5
    - docker ps -f name=studyshare-frontend-deploy
    - if [ $(docker ps -f name=studyshare-frontend-deploy --format "{{.Names}}") != "studyshare-frontend-deploy" ]; then echo "Frontend container failed to start"; exit 1; fi
