stages:
  - build
  - deploy

default:
  image: docker:20.10.16        # Docker CLI
  tags:
    - docker                   # make sure your runner has this tag
variables:
  # Point the Docker CLI at the host's socket
  DOCKER_HOST: "unix:///var/run/docker.sock"
  # Optional proxy settings if still needed
  HTTP_PROXY: "http://proxy.hof-university.de:3128"
  HTTPS_PROXY: "http://proxy.hof-university.de:3128"
  NO_PROXY: "localhost,127.0.0.1"

# Build the backend on the host Docker daemon
build_backend:
  stage: build
  script:
    - echo "Building backend image studyshare-backend:$CI_COMMIT_REF_SLUG"
    - docker build \
        -t studyshare-backend:$CI_COMMIT_REF_SLUG \
        -f backend/Dockerfile backend/

# Build the frontend on the host Docker daemon
build_frontend:
  stage: build
  script:
    - echo "Building frontend image studyshare-frontend:$CI_COMMIT_REF_SLUG"
    - docker build \
        --build-arg VITE_API_URL="$VITE_API_URL_GITLAB_CI" \
        -t studyshare-frontend:$CI_COMMIT_REF_SLUG \
        -f frontend/Dockerfile frontend/

# Deploy (stop + run) the backend on the host
deploy_backend:
  stage: deploy
  needs:
    - build_backend
  script:
    - echo "Deploying backend container"
    - docker rm -f studyshare-backend-deploy || true
    - docker run -d \
        --name studyshare-backend-deploy \
        -p 8080:8080 \
        studyshare-backend:$CI_COMMIT_REF_SLUG
    - docker ps -f name=studyshare-backend-deploy

# Deploy (stop + run) the frontend on the host
deploy_frontend:
  stage: deploy
  needs:
    - build_frontend
  script:
    - echo "Deploying frontend container"
    - docker rm -f studyshare-frontend-deploy || true
    - docker run -d \
        --name studyshare-frontend-deploy \
        -p 5173:80 \
        studyshare-frontend:$CI_COMMIT_REF_SLUG
    - docker ps -f name=studyshare-frontend-deploy