stages:
  - build
  - deploy

default:
  image: docker:20.10.16
  tags:
    - docker
variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"
  HTTP_PROXY: "http://proxy.hof-university.de:3128"
  HTTPS_PROXY: "http://proxy.hof-university.de:3128"
  NO_PROXY: "localhost,127.0.0.1"

build_backend:
  stage: build
  script:
    - docker info
    - echo "Building backend image"
    - cd backend
    - docker build -t studyshare-backend:$CI_COMMIT_REF_SLUG .

build_frontend:
  stage: build
  script:
    - |
      cat > frontend/.env.production <<EOF
      VITE_API_URL=$VITE_API_URL_GITLAB_CI
      EOF
    - cd frontend
    - npm ci
    - npm run build
    - cd ..
    - docker build -t studyshare-frontend:$CI_COMMIT_REF_SLUG -f frontend/Dockerfile .

deploy_backend:
  stage: deploy
  needs:
    - build_backend
  script:
    - docker rm -f studyshare-backend-deploy || true
    - docker run -d --name studyshare-backend-deploy -p 8080:8080 studyshare-backend:$CI_COMMIT_REF_SLUG
    - docker ps -f name=studyshare-backend-deploy

deploy_frontend:
  stage: deploy
  needs:
    - build_frontend
  script:
    - docker rm -f studyshare-frontend-deploy || true
    - docker run -d --name studyshare-frontend-deploy -p 5173:80 studyshare-frontend:$CI_COMMIT_REF_SLUG
    - docker ps -f name=studyshare-frontend-deploy