services:
  # Backend Service (Java Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: studyshare-backend-local
    ports:
      - "8080:8080" 
      - "5005:5005" # For remote debugging
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 # For remote debugging
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/studyshare_db
      - SPRING_DATASOURCE_USERNAME=studyshare_user
      - SPRING_DATASOURCE_PASSWORD=12EKA-02dD26oC1_2aA)
    volumes:
      - ./backend/target:/app/target 
    networks:
      - studyshare-network

  # Database Service (MariaDB)
  mariadb:
    image: mariadb:10.11 
    container_name: studyshare-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: K+d36o0tFRn@
      MARIADB_DATABASE: studyshare_db 
      MARIADB_USER: studyshare_user 
      MARIADB_PASSWORD: 12EKA-02dD26oC1_2aA)
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - studyshare-network

  # Frontend Service (React Vite)
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    container_name: studyshare-frontend-local
    ports:
      - "5173:80"
    
    depends_on:
      - backend 
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    networks:
      - studyshare-network 


networks:
  studyshare-network:
    driver: bridge 

volumes:
  mariadb_data:
    driver: local